title: Kevin Keen
email: kevin.keen99@gmail.com
description: "Call me Keen. A Product/UX Designer with a focus on UX/UI, visual design, product development, design systems, and data visualization."
url: "https://thekeendesigns.github.io/"

social:
  name: Kevin Keen
  links:
    - https://www.linkedin.com/in/kevin-keen-994b20144
    - https://github.com/thekeendesigns
    - https://dribbble.com/kkeena

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-primer
