title: Kevin Keen
email: kevin.keen99@gmail.com
description: "My name is Kevin Keen. Call me Keen. A eccentric Product Designer with a focus on UX/UI, visual design, product development, design systems, and data visualization."
url: "https://thekeendesigns.github.io/"

social:
  name: Kevin Keen
  links:
    - https://www.linkedin.com/in/kevin-keen-994b20144
    - https://github.com/thekeendesigns
    - https://www.behance.net/kevinkeen9a8a1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: jekyll-theme-primer
